routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

	$Category=App\Category::where('status', 1)->get();
    $prod=App\Product::where('qty','>','0')->where('status', 1)->get();
     return view('welcome',['category'=>$Category,'producto' => $prod]);
});

Route::get('catalogo/', function () {

    $Category=App\Category::where('status', 1)->get();
     $prod=App\Product::where('qty','>','0')->where('status', 1)->get();
     return view('catalogo',['category'=>$Category,'producto' => $prod]);
});

Route::get('contacto/', function () {

     return view('contacto');
});


//inyeccion de dependecnias
Route::bind('product',function($id){
return App\Product::where('id',$id)->first();
});

Route::get('detalle/{id}', 'ProductsController@detalle')->name('productos.detalle');
Route::get('productos/deleteIm/{id}', 'ProductsController@deleteIm')->name('deleteIm');
Route::get('productos/buscar/{name}', 'ProductsController@buscar')->name('buscarIm');
Auth::routes();
Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

//Route::get('/categorias','CategorysController@index')->name('categorias');
//Route::apiResource('/categorias','CategorysController@index');
Route::Resource('categorias','CategorysController');
Route::Resource('productos','ProductsController');
Route::get('/compras/cuenta','ComprascartController@cuenta')->middleware('auth')->name('compras.cuenta');
Route::get('/compras/cliente','ComprascartController@cliente')->middleware('auth')->name('compras.cliente');
Route::Resource('compras','ComprascartController');
Route::Resource('Cdetalle','ComprasdetalleController');
Route::get('verificarCliente/','ComprascartController@verificar');

Route::post('/compraMes','ComprascartController@compraMes');
Route::get('/TopMes','ComprascartController@TopMes');
Route::get('/graficos','ComprascartController@graficos');



//
Route::Resource('Sugerencias','SugerenciasController');
Route::get('EnvioSug','SugerenciasController@envio')->middleware('auth')->name('sugerencia.cliente');
/*Funcionalidad del carrito*/
Route::get('/cart/show', 'CartController@show')->name('cart.show');//ver Carrito d compras
Route::get('/cart/add/{product}', 'CartController@add')->name('cart.add');//añadir items
Route::get('/cart/delete/{product}', 'CartController@delete')->name('cart.delete');//quitar items
Route::get('/cart/trash', 'CartController@trash')->name('cart.trash');//vaciar Carritos
Route::get('/cart/update/{product}/{qty}', 'CartController@update')->name('cart.update');//actualizar cantidad
Route::get('/cart/detail', 'CartController@Detail')->middleware('auth')->name('cart.detail');//detalle del carrito
Route::get('/cart/proccess','CartController@proccess')->name('cart.proccess');
Route::get('/productos/destacar/{id}/{vl}', 'ProductsController@destacar')->name('productos.destacar');//ver Carrito d compras
/////////////////////////////////////////////////////////////
Route::get('pdf','ProductsController@pdf')->name('pdf.producto');
Route::get('minpdf','ProductsController@minpdf');
Route::get('pdfVentaC','ComprascartController@pdfVentaC');
Route::get('voucher/{id}','ComprascartController@voucher');


////////////////////////////////////////////////////////////////

Route::Resource('banco','BancosController');
Route::Resource('tipo-pago','TipopagoController');
Route::get('/banco/status/{id}/{st}','BancosController@status')->name('banco.status');
Route::Resource('envio','EnviosController');
Route::get('/envios/status/{id}/{st}','EnviosController@status')->name('envio.status');


Route::get('/salir', function () {
    Auth::logout();
    return redirect()->intended('/');
})->middleware('auth');

//vista min max
Route::get('/stockmin', function () { $prod=App\Product::where('qty','<=','10')->get();
     return view('productos.stockmin',compact('prod'));
})->middleware('auth');

Route::get('/top', function () {
 $prod=App\Product::where('qty','<=','50')->get();
/*$prod=App\Compras_cart_detalle::select('products_id', DB::raw('SUM(qty) as total_sales'))
                ->groupBy('products_id')
                ->havingRaw('SUM(qty) > 10')
                ->get();*/
                return $prod;


     return view('productos.stockmax',compact('prod'));
})->middleware('auth');


Route::get('/verificar', function () {
   $user="";
   $iva="";

     return view('ventas.verficar',compact('user','iva'));
})->middleware('auth');
Route::get('confirmar/{id}','ComprascartController@confirmar');
Route::get('verificarCliente/','ComprascartController@verificar');
Route::post('ingreso/','ComprascartController@ingreso');
Route::get('despacho','ComprascartController@verdespacho');
Route::post('Procesadespacho','ComprascartController@procesardespacho');
Route::get('buscadespacho','ComprascartController@buscadespacho');
Route::get('procesabusqueda','ComprascartController@procesabusqueda');


Route::Resource('usuario','UsersController');
Route::get('reset/{id}','UsersController@reset');
Route::get('logs','UsersController@logs');
Route::get('perfil', function () {

    $log=App\Log::where('user_id','=',auth()->id())->orderBy('created_at', 'desc')->take(15)->get();
return view('user.perfil',compact('log'));
 
})->middleware('auth');

Route::get('busca/cliente/{cedula}/{nac}','UsersController@busc_cliente');
//factura fiscal 
Route::get('/factura', function () {
$iva=App\Iva::find(1);
  $banco=App\Banco::where('status',1)->get();
        $tipo=App\Tipo_pago::where('status',1)->get();
         $envio=App\Envio::where('status',1)->get();
     return view('ventas.factura',compact('iva','banco','tipo','envio'));
})->middleware('auth');


//log
Route::get('/log', function () {
$log="";
$user=App\User::where('admin','<>','1')->get();
 
     return view('log.index',compact('log','user'));
})->middleware('auth');


Route::get('/Pventas', function () {
$ventas=""; 
$f1="";
$f2="";
     return view('ventas.mensual',compact('ventas','f1','f2'));
})->middleware('auth');

Route::get('/pdfcompraMes','ComprascartController@pdfcompraMes')->middleware('auth');
Route::get('/pdfTopMes','ComprascartController@pdfTopMes')->middleware('auth');
Route::get('/listadespacho','ComprascartController@listadespacho')->middleware('auth');
Route::get('/historicodespacho','ComprascartController@historicodespacho')->middleware('auth');



Route::get('/Topventas', function () {
$top=""; 
$f1="";
$f2="";
     return view('ventas.toVendido',compact('top','f1','f2'));
})->middleware('auth');

Route::get('/inbox', function () {
$Sug=App\Sugerencia::all();
    return view('mailbox.index',compact('Sug'));
})->middleware('auth');

Route::Resource('day','dayController');

resources/views/categorias/index.blade.php
@extends('layouts.admin')

@section('content')

<section class="content-header">
      <h1>
        Categorias 
        <small>(Productos)</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="home.php"><i class="fa fa-home"></i> Inicio</a></li>
        <li><a href="#"><i class="fa fa-cogs"></i> Configuraciones</a></li>
        <li class="active">Categorias</li>
      </ol>
    </section>

     <section class="content">
      
      <!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title"><strong></strong></h3>
         

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
          </div>
        </div>
        <div class="box-body">


          <div class="col-md-6">
             <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title"></h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
               @if (session('message'))
                   <div class="callout callout-success">
                <h4><i class="icon fa fa-check"></i> Notificación !</h4>

                <p>{{ session('message') }}</p>
              </div>
                        
                @endif
            <form method="POST" action="categorias" novalidate="">
               @csrf
                 <div class="form-group {{ $errors->has('Categoria') ? 'has-error' : '' }}">
                  <label class="control-label" for="inputError"> Definir Categoria</label>
                  <input type="text" class="form-control" name="Categoria" id="Categoria" value="{{ old('Categoria') }}" placeholder="">
                   <span class="help-block">{{ $errors->first('Categoria') }}</span>
                   
                  <input type="hidden" name="_token" value="{{ csrf_token() }}">
                  
                 
                  
                </div>

                <hr>
                  <center>
                <button type="submit" class="btn btn-primary" ><i class="fa fa-check-circle"></i> Guardar Categoria</button>

                <button type="reset" class="btn btn-default" ><i class="fa fa-trash"></i>Limpiar</button>
                  </center>
              </form>
            </div>
          </div>
          </div>
      
    
        <!--end col-md-6-->

        <div class="col-md-6">
           <div class="box">
            <div class="box-header with-border">
              <h3 class="box-title">Categorias Creadas</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table class="table table-bordered">
                <tr>
                  <th >#</th>
                  <th>Descripción</th>
                  <th>Status</th>
                  <th></th>
                </tr>
                @foreach ($Category as $Cat)
                  
                
                <tr>
                  <td>{{ $Cat->id }}</td>
                  <td>{{ $Cat->name }}</td>
                  <td>                    
                    @if($Cat->status==1)
                    <span class="badge bg-green">Habilitada</span>
                    @endif

                    @if($Cat->status==9)
                    <span class="badge bg-red">Inhabilitada</span>
                    @endif

                    
                  </td>
                  <td>
                    <center>
                      @if($Cat->status==1)
                   <a href="{{ route('categorias.edit',$Cat->id) }}" class="btn btn-default " >Inactivar</a>
                    @endif

                    @if($Cat->status==9)
                    <a href="{{ route('categorias.edit',$Cat->id) }}"> 
                    <button class=" btn btn-default  ">Activar</button>
                  </a>
                    @endif
                
                    <button class=" btn btn-info  " title="Editar" data-toggle="modal" data-target="#exampleModal{{$Cat->id}}" ><i class="fa fa-edit"></i></button>

                  <!--
                    <a href="{{ route('categorias.destroy',$Cat->id) }}" >
                      <button class=" btn btn-danger  " title="Eliminar Categoria" ><i class="fa fa-trash"></i></button>


                    </a>-->

                     <a href="#" class="btn btn-danger" data-toggle="modal" data-target="#data-delete{{$Cat->id}}" ><i class="fa fa-trash"></i></a>
    
                    </center>
                  </td>
                </tr>
                
                @endforeach
                
              </table>

             
            </div>
            <!-- /.box-body -->
            <div class="box-footer clearfix">
              {{ $Category->links()}}
            </div>
          </div>
          <!-- /.box -->
          
        </div>
       
      </div>
      <!-- /.box -->

    </section>



<!-- Modal -->
@foreach ($Category as $Cat)
<div class="modal fade" id="exampleModal{{$Cat->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editar Categoria</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <form method="POST" action="{{action('CategorysController@update',$Cat->id)}}" novalidate="">
               @csrf
          <div class="form-group {{ $errors->has('Categoria') ? 'has-error' : '' }}">
                  <label class="control-label" for="inputError"> Nombre Categoria</label>
                  <input type="text" class="form-control" name="Categoria" id="categoria" value="{{$Cat->name}}" >

                   <span class="help-block">{{ $errors->first('Categoria') }}</span>
                   
                    <input type="hidden" name="_method"value="PUT">
                    <input type="hidden" name="_token"value="{{ csrf_token()}}">
                 
                  
                 
                  
                </div>

                <hr>
                  <center>
                <button type="submit" class="btn btn-primary" ><i class="fa fa-check-circle"></i> Guardar Cambios</button>

          
                  </center>
              </form>
      
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
        
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="data-delete{{$Cat->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Eliminar La Categoria ({{$Cat->name}})</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <center>
        ¿Realmente desea Eliminar La Categoria ?
      </center>
        <form action="{{action('CategorysController@destroy',$Cat->id)}}" method="POST">
        <input type="hidden" name="_method"value="DELETE">
        <input type="hidden" name="_token"value="{{ csrf_token()}}">

          <hr>

          <center>
            <input type="submit" name="" value="Confirmar" class="btn btn-danger">
            <a href="#" data-dismiss="modal" class="btn btn-default">
              Cancelar

            </a>
          </center>
        </form>
       
      </div>
      <div class="modal-footer">
       
      </div>
    </div>
  </div>
</div>


@endforeach
<!--cierro div-->    

<script type="text/javascript">

  function llenado(id,name){

    $('#categoria').val(name);
    $('#id_cat').val(id_cat);
  
  }
  
</script>

@endsection